SELECT
    id,
    legacy_id,
    `group`,
    `type`,
    kind,
    `description`,
    CAST(JSON_EXTRACT_SCALAR(amount, '$.value') AS NUMERIC) AS amount_usd,
    CAST(JSON_EXTRACT_SCALAR(amount_in_host_currency, '$.value') AS NUMERIC) AS amount_in_host_currency_usd,
    host_currency_fx_rate,
    CAST(JSON_EXTRACT_SCALAR(net_amount, '$.value') AS NUMERIC) AS net_amount_usd,
    CAST(JSON_EXTRACT_SCALAR(net_amount_in_host_currency, '$.value') AS NUMERIC) AS net_amount_in_host_currency_usd,
    CAST(JSON_EXTRACT_SCALAR(tax_amount, '$.value') AS NUMERIC) AS tax_amount_usd,
    platform_fee,
    host_fee,
    payment_processor_fee,
    from_account,
    to_account,
    expense,
    `order`,
    created_at,
    updated_at,
    is_refunded,
    is_refund,
    is_disputed,
    is_in_review,
    payment_method,
    payout_method,
    is_order_rejected,
    merchant_id,
    invoice_template,
    host
FROM `open_collective`.expenses
